name: ZeroTier Direct Windows RDP

on:
  workflow_dispatch:

jobs:
  build-rdp:
    runs-on: windows-latest
    steps:
      - name: Enable Remote Desktop
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Set RDP Password
        run: |
          net user runneradmin "RdpPassword123!"

      - name: Install & Connect ZeroTier
        run: |
          winget install --id ZeroTier.ZeroTierOne -e --silent
          Start-Sleep -Seconds 10
          cd "C:\Program Files (x86)\ZeroTier\One"
          .\zerotier-cli.bat join f3797ba7a893d11e

      - name: Keep Runner Alive
        run: |
          Write-Host "RDP and ZeroTier are ready. Press Ctrl+C to stop."
          Start-Sleep -Seconds 21600
          
