name: ZeroTier Direct Windows RDP

on:
  workflow_dispatch:

jobs:
  build-rdp:
    runs-on: windows-latest
    steps:
      - name: Enable Remote Desktop
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Set RDP Password
        run: |
          net user runneradmin "RdpPass123456!"

      - name: Install & Connect ZeroTier
        run: |
          $msiUrl = "https://download.zerotier.com/dist/ZeroTier%20One.msi"
          Invoke-WebRequest -Uri $msiUrl -OutFile "ZeroTierOne.msi"
          Start-Process msiexec.exe -ArgumentList "/i ZeroTierOne.msi /quiet /norestart" -Wait
          Start-Sleep -Seconds 10
          zerotier-cli join ${{ secrets.ZEROTIER_NETWORK_ID }}

      - name: Keep Alive RDP
        run: |
          $i = 0
          while ($i -lt 360) {
            Start-Sleep -Seconds 60
            $i++
          }
          
